calendar, modal windows, basic logic
neodavis/CalendarApp pull request #1
Opened 2022-12-02 10:06 UTC by neodavis

2022-12-02 13:16 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.ts
> +
старайся пустые места проверять и чистить, это бросается в глаза и выглядит неаккуратно

2022-12-02 13:18 UTC, alexreview21 commented on src/app/components/dialogs/submit/submit.component.ts
> +      console.table(this.result) // Потом этот обьект будет лежать в масиве, в сторедже ngrx
консоли старайся не пушить, за них обычно "ругают"

2022-12-02 13:18 UTC, alexreview21 commented on src/app/components/dialogs/submit/submit.component.html
> +            <mat-option value="decree">Дикретна</mat-option>
дропни декрет, у нас только больничный и отпуск)

2022-12-05 13:09 UTC, alexreview21 requested changes

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.html
> +        <button mat-raised-button color="primary" (click)="go(-1)"><</button>
лучше не использовать магические цифры в коде
проще сделать методы next, prev чтоб описать то, что ты хочешь - движение по месяцам

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.html
> +          <td *ngFor="let day of week.days" [ngClass]="{'disabled': day.disabled, 'today': day.current}" (click)="details(day)">
методы нельзя называть существительными
должен быть глагол
например - getDayDetails или что-то подобное

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.html
> +          <li *ngIf="current.abcence.length === 0">На эту дану немає запланованих відпусток</li>
не обязательно проверять на длину равную 0
можно просто сделать 
`*ngIf="!current.abcence.length"`

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.scss
> +  th {
нужно избегать написания стилей по тегам
используй классы

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.ts
> +  @Input() data: any = [];
напиши тип вместо any

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/calendar/calendar.component.ts
> +  build(now: moment.Moment) {
лучше называть методы начиная с set, get

в данном случае setCalendar - сразу понятно, что происходит внутри

2022-12-05 13:09 UTC, alexreview21 commented on src/app/components/dialogs/submit/submit.component.ts
> +    startControl: new FormControl('', [Validators.required]),
нужно добавить валидацию, что startControl не может быть позже чем endControl

2022-12-05 13:09 UTC, alexreview21 commented on src/app/pipe/moment.pipe.ts
> +export class MomentPipe implements PipeTransform {
неудачное название пайпы
лучше бы дать название, которое даст четко понимание, что она делает
например formatDate или что-то подобное

2022-12-05 13:09 UTC, alexreview21 commented on src/app/service/data.service.ts
> +export class DataService {
лучше называть методы более специфично
это название максимально абстрактное и не понятно, что делает этот сервис

2022-12-05 14:31 UTC, AlexanderAndreyev requested changes

2022-12-05 14:31 UTC, AlexanderAndreyev commented on src/app/app.module.ts
> +import { DateFormatPipe } from './pipe/dateFormat.pipe';
camelCase файлы называть не нужно)

2022-12-05 14:31 UTC, AlexanderAndreyev commented on src/app/components/calendar/calendar.component.scss
> +  mat-card {
по тегам все еще стили написаны =)

2022-12-05 14:31 UTC, AlexanderAndreyev commented on src/app/components/calendar/calendar.component.ts
> +  @Input() data: Array<Object> = [];
Array<Object> это не тип
ты должен реальный тип прописать, создать свой

2022-12-05 14:31 UTC, AlexanderAndreyev commented on src/app/components/dialogs/submit/submit.component.ts
> +    startControl: new FormControl('', [Validators.required]),
валидатор сюда нужно добавить лучше, а не в html

2022-12-05 14:31 UTC, AlexanderAndreyev commented on src/app/pipe/dateFormat.pipe.ts
> +  name: 'DateFormat',
camelCase в названии пайпы нужен) не с большой буквы

2022-12-05 15:31 UTC, AlexanderAndreyev requested changes

2022-12-05 15:31 UTC, AlexanderAndreyev commented on src/app/components/calendar/calendar.component.ts
> +    console.log(this.current);
почисти вызовы консоли)

2022-12-05 15:31 UTC, AlexanderAndreyev commented on src/app/components/dialogs/submit/submit.component.ts
> +  return null
точки с запятой куда-то пропали)

2022-12-05 15:35 UTC, alexreview21 requested changes

2022-12-05 15:35 UTC, alexreview21 commented on src/app/components/dialogs/submit/submit.component.ts
> +  return null
точки с запятой)

2022-12-05 15:45 UTC, alexreview21 approved these changes

2022-12-05 15:48 UTC, merged