jwt authification
neodavis/CalendarApp pull request #8
Opened 2022-12-28 09:53 UTC by neodavis

2022-12-28 10:38 UTC, alexreview21 requested changes

2022-12-28 10:38 UTC, alexreview21 commented on apps/backend/src/app/absence/absence.dto.ts
> +  @IsInt()
camelCase?

2022-12-28 10:38 UTC, alexreview21 commented on apps/backend/src/app/absence/absence.entity.ts
> +  user_id: number;
вообще это нужно делать через релейшены)
OneToMany, OneToOne и так далее
нужно такой подход выбрать, почитай плз

2022-12-28 10:38 UTC, alexreview21 commented on apps/backend/src/app/app.controller.ts
> +  getAbsences(@Param('id', ParseIntPipe) id: number): Promise<AbsenceEntity[]> {
неа =)
тебе нужно из jwt токена, который ты должен отправлять на бек в запросе, доставать айдишник - так получается у тебя может любой человек украсть данные другого, просто зная его айдишку

2022-12-28 10:38 UTC, alexreview21 commented on apps/backend/src/app/app.controller.ts
> +  @Post('user/login/')
вынеси все, что связано с юзером - в отдельный контроллер

2022-12-28 10:38 UTC, alexreview21 commented on apps/backend/src/app/user/user.entity.ts
> +  public token: string;
токен нельзя хранить в базе)

2022-12-28 10:38 UTC, alexreview21 commented on apps/backend/src/app/user/user.service.ts
> +                password: user.password,
пароль в чистом виде ложить нельзя в базу) нужно хешировать, чтоб если база скомпрометируется - доступа все равно не было как минимум

2022-12-28 10:38 UTC, alexreview21 commented on apps/frontend/src/app/components/dialogs/register/register.component.ts
> +        user_id: Math.round((Math.random()*100000)),
айдишник должен генериться на беке, нельзя на фронте)

2022-12-28 10:38 UTC, alexreview21 commented on apps/frontend/src/app/components/dialogs/login/login.component.ts
> +      this.store.dispatch(UserActions.userLogin({
честно говоря не вижу смысла для регистрации и логина прикручивать ngrx - это чисто банальные простые формочки и и состояние спокойно менеджится внутри этого компонента

2022-12-28 10:38 UTC, alexreview21 commented on apps/frontend/src/app/app.component.ts
> +    this.token$ = this.store.select(tokenSelector)
не вижу чтоб ты этот токен хоть как-то использовал
а его нужно в запрос ложить)

2022-12-29 14:56 UTC, alexreview21 requested changes

2022-12-29 14:56 UTC, alexreview21 commented on apps/backend/src/app/absence/absence.controller.ts
> +  @Get('absences/get/:token/')
ноуп)
нужно сделать примерно как тут - https://docs.nestjs.com/security/authentication
так нельзя токен передавать
его нужно передавать в хедере запроса)

2023-01-03 14:22 UTC, alexreview21 requested changes

2023-01-03 14:22 UTC, alexreview21 commented on apps/backend/src/app/absence/absence.controller.ts
> +    return this.absenceService.deleteAbsence(id, token);
а зачем тебе токен, чтоб удалить эбсенс по его же айдишнику?)

2023-01-03 14:22 UTC, alexreview21 commented on apps/backend/src/app/absence/absence.entity.ts
> +  userId: number;
тут должен был релейшен) OneToMany/ManyToOne и так далее, посмотри в эту сторону

2023-01-03 14:22 UTC, alexreview21 commented on apps/backend/src/app/absence/absence.service.ts
> +      const data = this.jwtService.verify(token);
может не data, а user?)

2023-01-03 14:22 UTC, alexreview21 commented on apps/backend/src/app/app.controller.ts
> +export class AppController { }
файл пустой, удали его

2023-01-03 14:22 UTC, alexreview21 commented on apps/backend/src/app/auth/local.strategy.ts
> +            throw new NotFoundException("Неправильний логін або пароль");
401, а не 404)

2023-01-03 14:22 UTC, alexreview21 commented on apps/backend/src/app/user/user.service.ts
> +    public async validate(username: string, password: string): Promise<UserEntity | null> {
метод validate судя по названию должен возвращать true/false,  а не юзера)

2023-01-03 14:22 UTC, alexreview21 commented on apps/frontend/src/app/components/calendar/calendar.component.ts
> +    if (sessionStorage.getItem('token')) {
а зачем эта проверка?

2023-01-03 14:22 UTC, alexreview21 commented on apps/frontend/src/app/components/dialogs/register/register.component.ts
> +            this.close();
у тебя регистрация и логин должны быть отдельными роутами на фронтенде, а не попапом)

https://angular.io/guide/routing-overview

2023-01-03 14:22 UTC, alexreview21 commented on apps/frontend/src/app/shared/interfaces/user.ts
> +    user_id: number;
camelCase

2023-01-03 14:22 UTC, alexreview21 commented on apps/frontend/src/app/shared/service/absence-backend.service.ts
> +    return this.http.get<Absence[]>((isDevMode() ? 'http://localhost:3333' : "https://calendarapp-production-6494.up.railway.app") + '/api/absence/get/');
зачем копипастить это по несколько раз? вынеси в отдельный метод эту логику с путем к беку)

2023-01-04 12:47 UTC, AlexanderAndreyev requested changes

2023-01-04 12:47 UTC, AlexanderAndreyev commented on apps/frontend/src/app/components/register/register.component.ts
> +              this.router.navigate(['/login']);
после регистрации ты сразу должен попадать на календарик, а не на логин)

2023-01-04 12:47 UTC, AlexanderAndreyev commented on apps/frontend/src/app/components/login/login.component.ts
> +            this.router.navigate(['/']);
'/calendar'?

2023-01-04 12:47 UTC, AlexanderAndreyev commented on apps/frontend/src/app/components/login/login.component.ts
> +            this.store.dispatch(AbsenceActions.getAbsences());
этот экшин уже на самом календаре нужно вызвать) так семантически получается не оч

2023-01-04 12:47 UTC, AlexanderAndreyev commented on apps/frontend/src/app/components/header/header.component.html
> +        *ngIf="sessionStorage.getItem('token')">Головна</button>
ойойой, а точно это нужно?

2023-01-04 12:48 UTC, AlexanderAndreyev requested changes

2023-01-04 12:48 UTC, AlexanderAndreyev commented on apps/frontend/src/app/app.module.ts
> +  { path: '', component: CalendarComponent, canActivate: [AuthGuard] },
calendar)

2023-01-04 13:32 UTC, AlexanderAndreyev approved these changes

2023-01-04 14:46 UTC, merged